//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStop
    {
        public int RouteStopID { get; set; }
        public int OrderNumber { get; set; }
        public Nullable<int> ArrivalOffsetMinutes { get; set; }
        public Nullable<int> DepartureOffsetMinutes { get; set; }
        public int RouteID { get; set; }
        public int StopID { get; set; }
    
        public virtual Routes Routes { get; set; }
        public virtual Stops Stops { get; set; }
    }
}
