//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketID { get; set; }
        public int TripID { get; set; }
        public int SoldByUserID { get; set; }
        public int DestinationStopID { get; set; }
        public int SeatNumber { get; set; }
        public System.DateTime PurchaseDateTime { get; set; }
        public double Price { get; set; }
        public string Status { get; set; }
        public string TypeOfPayment { get; set; }
    
        public virtual Stops Stops { get; set; }
        public virtual Trips Trips { get; set; }
        public virtual Users Users { get; set; }
    }
}
