//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trips
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trips()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int TripID { get; set; }
        public int RouteID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public int BusID { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public System.DateTime ArrivalDateTime { get; set; }
        public double Price { get; set; }
        public int AvailableSeats { get; set; }
        public string Status { get; set; }
        public int DriverID { get; set; }
    
        public virtual Buses Buses { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Routes Routes { get; set; }
        public virtual Schedule Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
